name: Build Android APK
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK packages
        shell: bash
        run: |
          set -e
          export ANDROID_SDK_ROOT="$ANDROID_HOME"
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          ( yes | sdkmanager --licenses ) || true

      - name: Download Gradle 8.7
        run: |
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip

      - name: Show tree
        run: |
          sudo apt-get update && sudo apt-get install -y tree
          tree -a -L 4

      - name: Build debug APK (module :app)
        run: ./gradle-8.7/bin/gradle --no-daemon :app:assembleDebug --stacktrace

      - name: List outputs
        run: ls -R app/build/outputs || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
